class CfgGlasses {
    class None;
	
	#define FACE_PROTECTION(p1,p2,p3) class p1 : p2 {\
		RATING = p3##;\
	};

	FACE_PROTECTION(USP_M50_BLK,None,0.8)
    FACE_PROTECTION(USP_M50_FC_BLK,None,0.9)
    FACE_PROTECTION(USP_FM12_BLK,None,0.7)
    FACE_PROTECTION(USP_FM12_FC_BLK,USP_FM12_BLK,0.9)
    FACE_PROTECTION(USP_GP21_BLK,None,0.7)
    FACE_PROTECTION(USP_GP21_FC_BLK,USP_GP21_BLK,0.9)
    FACE_PROTECTION(USP_SOTR,None,0.6)
    FACE_PROTECTION(USP_SOTR_SMB1,None,0.6)
    FACE_PROTECTION(USP_SOTR_SMB2,None,0.6)
    FACE_PROTECTION(USP_SOTR_ADV_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_ADV_SMB1_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_ADV_SMB2_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_CRO_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_CRO_SMB1_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_CRO_SMB2_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_DET_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_DET_SMB1_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_DET_SMB2_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_ESS_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_ESS_SMB1_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_ESS_SMB2_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_GAT_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_GAT_SMB1_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_GAT_SMB2_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_MFR_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_MFR_SMB1_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_MFR_SMB2_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_OAK_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_OAK_SMB1_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_OAK_SMB2_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_RAI_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_RAI_SMB1_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_RAI_SMB2_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_SJA_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_SJA_SMB1_BLK,None,0.6)
    FACE_PROTECTION(USP_SOTR_SJA_SMB2_BLK,None,0.6)
};