name = "KJW's Medical Expansion"
prefix = "KJW_MedicalExpansion"
author = "KJW"
mainprefix = "y"

[files]
include = [
    "mod.cpp",
    "*.paa"
]

[version]
git_hash = 0 # Disabled

path = "addons/core/script_version.hpp" # Default